### ISSUE TITLE
Interrupting activity history may lead to corrupted state of the DB

### ISSUE THREAD

**Issue by jniznan** [calmrat/metrique#117] opened 2013-10-18 11:42 UTC
We removed the support for updating documents.
Now when we want to update documents we need to remove them and save them again (with the changes). 
If activity import is interrupted after the removal but before the saving then the objects will disappear from the DB.

Should we add back the support for updating docs?

**Comment by calmrat** [comment] 2013-10-22 07:40
i don't believe so; activity history import is a 'one time event' and is expected to be run first. We should focus on error detection and handling during activity import process instead. If any unrecoverable errors occur, the import should abort and we should drop the db and restart.

Another approach might be to journal all activity import object results locally to disk first, then only after the entire import has completed successfully, drop the remote metrique cube and push the updated objects + new objects?

**Comment by calmrat** [comment] 2013-10-24 23:13
maybe we _could_ add .update api call, which doesn't update in-place, but rather, completes the save new, remove old transaction?

**Comment by calmrat** [comment] 2013-11-19 19:30
"we need to remove them and save them again (with the changes)"; could you provide a generic example of when this is necessary? 

is the case when we want to update _start or _end? If so, what's the cause of the 'old' version needing to be removed?

could the workflow change such that the client would hold the object in it's 'first' state, get whatever information is needed to update the first state -> second state then only save the object after it's in it's final, desired state?

if we update _oid, it means we have a new, unique object. 

If we update any non "_" system field (eg, 'product') then the 'updated' object should case a new object state to be added (add _end to existing object, save new object with _end:null). And _hash is expected to be different

**Comment by calmrat** [comment] 2013-12-11 19:39
this will be resolved in 0.2.5; now activity_import runs client side and only saves to the db after each individual item is fully prepared; ie, each _oid has current value + all historical values; then and only then are all the objects saved as-is; so if anything fails while running activity_import, we can look to see which _oids don't yet exist on the server and force=[those _oids only]

**Comment by calmrat** [comment] 2014-02-18 20:12
resolved

**Closed as completed by calmrat** 2014-02-18 20:12 UTC
